#%xp% is changed with value.
#%xp% is working on almost every message.
#You can find player data in 'playerdata' folder.

use-xpbank: '&c/xpbank (use,withdraw,reload) (amount)'
error: '&cSomething went wrong.'
error-need-number: '&cYou need to enter number.'
success-add: '&aYou successfully added %xp% to bank.'
success-withdraw: '&aYou successfully withdraw %xp% from bank.'
you-have-xp: '&aYou have %xp% in bank.'
dont-have-permission: '&cYou dont have permission.'
reloaded-config: '&aSuccessfully reloaded config.'
invalid-args: '&c/xpbank (add,withdraw,reload) (amount)'
use-xpbank-menu: true #"/xpbank" menu

xp-bank-menu-title: '&aXPBank Menu'
menu-block: 'EMERALD_BLOCK' #!!!IMPORTANT!!! If this is an invalid name, the menu will not open.
error-wrong-item: '&cA Invalid item name is set in config.yml. Please tell this to a admin.'
menu-block-info: '&aYou have %xp% XP.'

